

PREFIX ns1: <file:/uploaded/generated/relationship/>
PREFIX cptsno: <file:/uploaded/generated/concept/snomed/>
PREFIX cpticd: <file:/uploaded/generated/concept/icd10/>
# CONSTRUCT GRAPH OF ANCESTORS OF ANXIETY!!!!!
CONSTRUCT {?sno_kid ns1:isSubclassOf ?sno_parent.} where { 
	cpticd:F41.9 ns1:map ?sno_kid .
    ?sno_kid ns1:isChildOf* ?sno_parent .
    ?sno_parent ns1:label ?label .
} limit 100 


PREFIX ns1: <file:/uploaded/generated/relationship/>
PREFIX cptsno: <file:/uploaded/generated/concept/snomed/>
PREFIX cpticd: <file:/uploaded/generated/concept/icd10/>
# SELECT ALL ANCESTORS OF ANXIETY!!!!!
select * where { 
	cpticd:F41.9 ns1:map ?o .
    ?o ns1:isChildOf* ?o2 .
    ?o2 ns1:label ?lab .
} limit 100 


PREFIX ns1: <file:/uploaded/generated/relationship/>
PREFIX cptsno: <file:/uploaded/generated/concept/snomed/>
PREFIX cpticd: <file:/uploaded/generated/concept/icd10/>
# SELECT ANXIETY MAPS
select * where { 
	cpticd:F41.9 ns1:map ?o .
    ?o ns1:label ?lab .
} limit 100 


# SELECT neoplasm concepts
PREFIX ns1: <file:/uploaded/generated/relationship/>
PREFIX cpticd: <file:/uploaded/generated/concept/icd10/>
select ?s ?o where { 
    ?s ns1:label ?o .
    FILTER REGEX(?o, "neoplasm")
}


# RANDOM SELECTION OF iSChildOf and map CODES IN DB
# Yields labels only
PREFIX ns1: <file:/uploaded/generated/relationship/>
select ?s ?p ?o where { 
    ?s ?p ?o .
    FILTER (?p IN (ns1:map, ns1:isChildOf))
}
ORDER BY RAND() limit 100 


# RANDOM SELECTION OF ISA CODES IN DB
# Yields labels only
select * where { 
	?s ns1:isChildOf ?o .
} ORDER BY RAND() limit 100 



# RANDOM SELECTION OF THINGS IN DB
# Yeilds labels only
select * where { 
	?s ?p ?o .
} ORDER BY RAND() limit 100 








